const project = {
  photoUrls: Array.from(
    { length: 20 },
    (_, i) => `/photo_${(i + 1).toString().padStart(2, "0")}.png`,
  ),
  name: "ЖК на Слівенській",
  address:
    "Тернопіль, Східний, вул. Чайковського, вул. Малишка, вул. Слівенська",
  startPricePerSquareMeter: 800,
  apartments: [
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 3,
      area: 41.75,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 3,
      area: 41.75,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 3,
      area: 41.75,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 3,
      area: 70,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 3,
      area: 70,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 3,
      area: 70,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 3,
      sectionNumber: 3,
      area: 90,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 3,
      sectionNumber: 3,
      area: 90,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 3,
      sectionNumber: 3,
      area: 90,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
    },
  ],
};

export default project;
