const project = {
  photoUrls: Array.from(
    { length: 20 },
    (_, i) => `/photo_${(i + 1).toString().padStart(2, "0")}.png`,
  ),
  name: "ЖК на Слівенській",
  address:
    "Тернопіль, Східний, вул. Чайковського, вул. Малишка, вул. Слівенська",
  startPricePerSquareMeter: 800,
  apartments: [
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 3,
      area: 41.75,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_1.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 3,
      area: 44.22,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_2.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 3,
      area: 45.06,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_3.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 1,
      area: 45.4,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_4.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 1,
      area: 46.63,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_5.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 2,
      area: 48.67,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_6.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 1,
      area: 50.57,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_7.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 1,
      sectionNumber: 3,
      area: 50.91,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_8.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 2,
      area: 66.08,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_9.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 1,
      area: 66.65,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_10.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 2,
      area: 66.67,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_11.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 2,
      area: 67.31,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_12.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 2,
      area: 70.96,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_13.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 2,
      area: 71.8,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_14.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 1,
      area: 72.52,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_15.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 2,
      sectionNumber: 2,
      area: 74.03,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_16.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 3,
      sectionNumber: 3,
      area: 89.97,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_17.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 3,
      sectionNumber: 3,
      area: 89.97,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_18.webp",
    },
    {
      pricePerSquareMeter: 800,
      roomsCount: 3,
      sectionNumber: 1,
      area: 91.29,
      releaseDate: "4 кв. 2025",
      floors: "1-7",
      status: "будується",
      imgUrl: "planning_19.webp",
    },
  ],
};

export default project;
